### GET Health
GET http://localhost:8888/health
Accept: application/json

### GET Products
GET http://localhost:8888/api/product
Accept: application/json

### Get product by ID
GET http://localhost:8888/api/product/2
Accept: application/json

### POST Create Product
POST http://localhost:8888/api/product
Content-Type: application/json

{
  "name": "Television",
  "price": 8000000,
  "stock": 30
}

### PUT Update Product
PUT http://localhost:8888/api/product/1 
Content-Type: application/json

{
  "name": "Gaming Laptop",
  "price": 25000000,
  "stock": 15
}

### DELETE Product
DELETE http://localhost:8888/api/product/4
Accept: application/json

// Categories
### GET Categories
GET http://localhost:8888/api/category
Accept: application/json  

### Get category by ID
GET http://localhost:8888/api/category/1
Accept: application/json    

### POST Create Category
POST http://localhost:8888/api/category
Content-Type: application/json

{
  "name": "Electronics",
  "description": "Devices and gadgets"
}

### PUT Update Category
PUT http://localhost:8888/api/category/1 
Content-Type: application/json

{
  "name": "Gaming Electronics",
  "description": "Devices and gadgets for gaming"
}

### DELETE Category
DELETE http://localhost:8888/api/category/4
Accept: application/json    