### GET Health
# GET http://localhost:8888/health
GET https://kasir-go-learn-production.up.railway.app/health
Accept: application/json

### GET Products
GET https://kasir-go-learn-production.up.railway.app/api/product
Accept: application/json

### Get product by ID
GET https://kasir-go-learn-production.up.railway.app/api/product/1
Accept: application/json

### POST Create Product
POST https://kasir-go-learn-production.up.railway.app/api/product
Content-Type: application/json

{
  "name": "Kulkas 2 pintu",
  "price": 2000000,
  "stock": 50,
  "category_id": 1
}

### PUT Update Product
PUT https://kasir-go-learn-production.up.railway.app/api/product/1 
Content-Type: application/json

{
  "name": "Gaming Laptop",
  "price": 25000000,
  "stock": 15,
  "category_id": 1,
  "category_name": "Electronics"
}

### DELETE Product
DELETE http://localhost:8888/api/product/4
Accept: application/json

// Categories
### GET Categories
GET https://kasir-go-learn-production.up.railway.app/api/category
Accept: application/json  

### Get category by ID
GET https://kasir-go-learn-production.up.railway.app/api/category/1
Accept: application/json    

### POST Create Category
POST https://kasir-go-learn-production.up.railway.app/api/category
Content-Type: application/json

{
  "name": "Electronics"
}

### PUT Update Category
PUT http://localhost:8888/api/category/1 
Content-Type: application/json

{
  "name": "Gaming Electronics"
}

### DELETE Category
DELETE http://localhost:8888/api/category/4
Accept: application/json    


// Transactions
### POST Checkout - Multiple Items
POST http://localhost:8888/api/checkout
Content-Type: application/json

{
  "items": [
    {
      "product_id": 1,
      "quantity": 1
    },
    {
      "product_id": 2,
      "quantity": 1
    },
    {
      "product_id": 3,
      "quantity": 1
    }
  ]
}

// Reports
### GET Daily Report (Hari Ini)
GET http://localhost:8888/api/report/hari-ini
Accept: application/json

### GET Report with Date Range
GET http://localhost:8888/api/report?start_date=2025-01-01&end_date=2025-02-28
Accept: application/json